spring.application.name=rabbitmq-producer
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Opcional logs:
logging.level.org.springframework.amqp=DEBUG